[tool.poetry]
name = "nvidia-interview"
version = "0.1.0"
description = ""
authors = ["Andreas Scheipers <andreas.scheipers@uniberg.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
